# Pandas

[Pandas](https://pandas.pydata.org/) è una libreria che ci permette di gestire dati in forma di tabella. Ha moltissime funzionalità, fra cui la possbilità di leggere e scrivere questi dati da moltissimi formati diversi.

Come al solito quando vogliamo usare un pacchetto non parte delle funzionalità di base di Python, partiamo installandolo con pip.

In [ ]:
!python -m pip install pandas

Requirement already satisfied: pandas in /home/ashmi/Lavoro/didattica/.venv/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in /home/ashmi/Lavoro/didattica/.venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ashmi/Lavoro/didattica/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/ashmi/Lavoro/didattica/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Ora controlliamo se l'installazione è andata a buon fine importandolo

In [2]:
import pandas as pd

## Cos'è un DataFrame?

Pandas viene utilizzato principalmente per creare delle strutture dati di tipo tablellare, che si chiamano DataFrame. Sono un po' come degli array NumPy bidimensionali, ma ci consentono di fare operazioni molto più sofisticate.

![dataframe pandas](images/pandas_dataframe.png)

Per creare un DataFrame possiamo partire da dizionari e liste Python nel modo seguente:

In [7]:
ghibli_movies = pd.DataFrame({
    "title" : ["Princess Mononoke", "Grave of the Fireflies", "Porco Rosso", "Tales from Earthsea"],
    "director" : ["Hayao Miyazaki", "Isao Takahata", "Hayao Miyazaki", "Gorō Miyazaki"],
    "saddest movie ever?" : [False, True, False, False],
    "year": [1997, 1988, 1992, 2006],
})

ghibli_movies

                    title        director  saddest movie ever?  year
0       Princess Mononoke  Hayao Miyazaki                False  1997
1  Grave of the Fireflies   Isao Takahata                 True  1988
2             Porco Rosso  Hayao Miyazaki                False  1992
3     Tales from Earthsea   Gorō Miyazaki                False  2006

# Indicizzazione di righe e colonne

Come per quanto riguarda dizionari, array, liste, possiamo indicizzare i contenuti dei nostri DataFrame usando le funzionalità appropriate.

Per accedere alle singole righe del nostro DataFrame come faremmo con una lista o un array usiamo l'attributo `iloc`:

In [8]:
print(ghibli_movies.iloc[0])

title                  Princess Mononoke
director                  Hayao Miyazaki
saddest movie ever?                False
year                                1997
Name: 0, dtype: object

Possiamo anche usare slicing:

In [9]:
ghibli_movies.iloc[1:3]

                    title        director  saddest movie ever?  year
1  Grave of the Fireflies   Isao Takahata                 True  1988
2             Porco Rosso  Hayao Miyazaki                False  1992

Oltre a poter scorrere le righe del DataFrame, possiamo anche ottenere il contenuto di una o più colonne:

In [12]:
# a single column
print(ghibli_movies["title"])

0         Princess Mononoke
1    Grave of the Fireflies
2               Porco Rosso
3       Tales from Earthsea
Name: title, dtype: str

In [13]:
# more than one column
ghibli_movies[["title","year"]]

                    title  year
0       Princess Mononoke  1997
1  Grave of the Fireflies  1988
2             Porco Rosso  1992
3     Tales from Earthsea  2006

Un'altra modalità di indicizzazione è quella per etichetta o label tramite l'attributo `loc`. Siccome non abbiamo specificato la modalità di indicizzazione del nostro DataFrame, per ora si comporta esattamente come `iloc`.

In [14]:
ghibli_movies.loc[1]

title                  Grave of the Fireflies
director                        Isao Takahata
saddest movie ever?                      True
year                                     1988
Name: 1, dtype: object

Questo comportamento dipende dall'indice (index) del nostro DataFrame. Proviamo a sostituire l'index con gli anni in cui sono stati rilasciati i tre film.

In [15]:
ghibli_movies.index = ghibli_movies["year"]

In [16]:
ghibli_movies

                       title        director  saddest movie ever?  year
year
1997       Princess Mononoke  Hayao Miyazaki                False  1997
1988  Grave of the Fireflies   Isao Takahata                 True  1988
1992             Porco Rosso  Hayao Miyazaki                False  1992
2006     Tales from Earthsea   Gorō Miyazaki                False  2006

A questo punto `.loc` si comporta in modo molto diverso!

In [17]:
# this doesn't work
ghibli_movies.loc[0]

KeyError: 0

In [18]:
# this works
ghibli_movies.loc[1997]

title                  Princess Mononoke
director                  Hayao Miyazaki
saddest movie ever?                False
year                                1997
Name: 1997, dtype: object

In [19]:
ghibli_movies.iloc[0]

title                  Princess Mononoke
director                  Hayao Miyazaki
saddest movie ever?                False
year                                1997
Name: 1997, dtype: object

Se non vogliamo avere la colonna `year` ripetuta, possiamo rimuoverla usando `del`

In [20]:
del ghibli_movies["year"]

ghibli_movies

                       title        director  saddest movie ever?
year
1997       Princess Mononoke  Hayao Miyazaki                False
1988  Grave of the Fireflies   Isao Takahata                 True
1992             Porco Rosso  Hayao Miyazaki                False
2006     Tales from Earthsea   Gorō Miyazaki                False

Oppure creare il dataframe specificando direttamente la colonna "index":

In [23]:
ghibli_movies = pd.DataFrame({
    "title" : ["Princess Mononoke", "Grave of the Fireflies", "Porco Rosso", "Tales from Earthsea"],
    "director" : ["Hayao Miyazaki", "Isao Takahata", "Hayao Miyazaki", "Gorō Miyazaki"],
    "saddest movie ever?" : [False, True, False, False]},
    index = [1997, 1988, 1992, 2006]
)


ghibli_movies

                       title        director  saddest movie ever?
1997       Princess Mononoke  Hayao Miyazaki                False
1988  Grave of the Fireflies   Isao Takahata                 True
1992             Porco Rosso  Hayao Miyazaki                False
2006     Tales from Earthsea   Gorō Miyazaki                False

Infine, se vogliamo mantenere il nome della colonna, possiamo assegnarlo usando l'attributo `name` della colonna `index`

In [24]:
ghibli_movies.index.name = "year"
ghibli_movies

                       title        director  saddest movie ever?
year
1997       Princess Mononoke  Hayao Miyazaki                False
1988  Grave of the Fireflies   Isao Takahata                 True
1992             Porco Rosso  Hayao Miyazaki                False
2006     Tales from Earthsea   Gorō Miyazaki                False

## Quiz

1. Nel DataFrame `ghibli_movies` estrai le colonne relative a direttore e titolo
2. Nel DataFrame `ghibli_movies` estrai le colonne relative a direttore e titolo dei film rilasciati dopo il 1990

In [28]:
# ES1
ghibli_movies[["title", "director"]]

                       title        director
year
1997       Princess Mononoke  Hayao Miyazaki
1988  Grave of the Fireflies   Isao Takahata
1992             Porco Rosso  Hayao Miyazaki
2006     Tales from Earthsea   Gorō Miyazaki

In [45]:
# ES2
ghibli_after_1990 = ghibli_movies.loc[[1992, 1997, 2006]]
ghibli_after_1990[["title", "director"]]

                    title        director
year
1992          Porco Rosso  Hayao Miyazaki
1997    Princess Mononoke  Hayao Miyazaki
2006  Tales from Earthsea   Gorō Miyazaki

## Indicizzazione avanzata

Oltre all'indicizzazione "semplice", Pandas ci consente di utilizzare dei filtri più sofisticati. Si tratta di un meccanismo che è analogo a quelli visti con NumPy. In pratica, possiamo selezionare le righe di un DataFrame che rispettano una qualche condizione. Partiamo con un esempio:

In [38]:
# Select movies by Miyazaki

ghibli_movies[ghibli_movies["director"] == "Hayao Miyazaki"]

                  title        director  saddest movie ever?
year
1997  Princess Mononoke  Hayao Miyazaki                False
1992        Porco Rosso  Hayao Miyazaki                False

Se una delle colonne contiene valori booleani, possiamo anche filtrare le righe del DataFrame usando direttamente la colonna booleana:

In [40]:
ghibli_movies

                       title        director  saddest movie ever?
year
1997       Princess Mononoke  Hayao Miyazaki                False
1988  Grave of the Fireflies   Isao Takahata                 True
1992             Porco Rosso  Hayao Miyazaki                False
2006     Tales from Earthsea   Gorō Miyazaki                False

In [39]:
ghibli_movies[ghibli_movies["saddest movie ever?"]]

                       title       director  saddest movie ever?
year
1988  Grave of the Fireflies  Isao Takahata                 True

Possiamo anche definire degli insiemi di valori per filtrare una colonna:

In [46]:
ghibli_movies[ghibli_movies.index.isin([1988,1997])]

                       title        director  saddest movie ever?
year
1997       Princess Mononoke  Hayao Miyazaki                False
1988  Grave of the Fireflies   Isao Takahata                 True

In [47]:
ghibli_movies[ghibli_movies.index >= 1990]

                    title        director  saddest movie ever?
year
1997    Princess Mononoke  Hayao Miyazaki                False
1992          Porco Rosso  Hayao Miyazaki                False
2006  Tales from Earthsea   Gorō Miyazaki                False

In [48]:
ghibli_movies_noindex = pd.DataFrame({
    "title" : ["Princess Mononoke", "Grave of the Fireflies", "Porco Rosso", "Tales from Earthsea"],
    "director" : ["Hayao Miyazaki", "Isao Takahata", "Hayao Miyazaki", "Gorō Miyazaki"],
    "saddest movie ever?" : [False, True, False, False],
    "year": [1997, 1988, 1992, 2006],
})

ghibli_movies_noindex[ghibli_movies_noindex["year"] >= 1990]

                 title        director  saddest movie ever?  year
0    Princess Mononoke  Hayao Miyazaki                False  1997
2          Porco Rosso  Hayao Miyazaki                False  1992
3  Tales from Earthsea   Gorō Miyazaki                False  2006

## Quiz

1. Seleziona i titoli dei film diretti da hayao miyazaki o goro miyazaki

In [53]:
g = ghibli_movies
g[g["director"].isin(["Hayao Miyazaki", "Gorō Miyazaki"])]

                    title        director  saddest movie ever?
year
1997    Princess Mononoke  Hayao Miyazaki                False
1992          Porco Rosso  Hayao Miyazaki                False
2006  Tales from Earthsea   Gorō Miyazaki                False

## Leggere e scrivere file

Per creare DataFrame, possiamo anche usare delle funzionalità apposite di Pandas, che ci consentono di leggere e scrivere file in una moltitudine di formati:

![pandas I/O](images/pandas_readwrite.svg)

Noi vedremo solo le funzionalità legate a CSV (almeno per ora). Per leggere un file CSV con Pandas usiamo la funzione `.read_csv`

In [54]:
academyawards = pd.read_csv("data/academyawards.csv")

academyawards

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast
0,Wings,tt0018578,1927,1929,"William A. Wellman, Harry d’Abbadie d’Arrast",Paramount Pictures,12,5
1,The Broadway Melody,tt0019729,1929,1930,Harry Beaumont,Metro-Goldwyn-Mayer,4,3
2,All Quiet on the Western Front,tt0020629,1930,1930,"Lewis Milestone, Nate Watt",Universal Pictures,22,6
3,Cimarron,tt0021746,1931,1931,Wesley Ruggles,RKO Pictures,13,6
4,Grand Hotel,tt0022958,1932,1932,Edmund Goulding,Metro-Goldwyn-Mayer,19,8
...,...,...,...,...,...,...,...,...
80,Spotlight,tt1895587,2015,2016,Tom McCarthy,"Anonymous Content, Participant",15,2
81,Moonlight,tt4975722,2016,2017,Barry Jenkins,"Plan B Entertainment, A24",6,2
82,The Shape of Water,tt5580390,2017,2018,Guillermo del Toro,"Searchlight Pictures, TSG Entertainment",8,3
83,Green Book,tt6966692,2018,2019,Peter Farrelly,"Universal Pictures, DreamWorks, Participant, A...",7,1
84,Parasite,tt6751668,2019,2020,Bong Joon-ho,"CJ Entertainment, Barunson E&A",5,5

Per scrivere un DataFrame in un file CSV possiamo applicare analogamente il metodo `to_csv`:

In [55]:
ghibli_movies.to_csv("output/ghibli.csv")

## Operazioni su colonne

In modo simile a quanto abbiamo visto per NumPy, possiamo applicare delle operazioni matematiche alle colonne del DataFrame. Prendiamo ad esempio la tabella dei film che abbiamo appena aperto. Per ottenere il numero totale di attori nel film possiamo scrivere:

In [56]:
academyawards["male_cast"] + academyawards["female_cast"]

0     17
1      7
2     28
3     19
4     27
      ..
80    17
81     8
82    11
83     8
84    10
Length: 85, dtype: int64

Oltre alle solite operazioni matematiche e booleane, possiamo anche applicare alcune operazioni a colonne composte di stringhe:

In [57]:
# make movie names lowercase
academyawards["movie"].str.lower()

0                              wings
1                the broadway melody
2     all quiet on the western front
3                           cimarron
4                        grand hotel
                   ...
80                         spotlight
81                         moonlight
82                the shape of water
83                        green book
84                          parasite
Name: movie, Length: 85, dtype: str

In [62]:
# check if a movie name contains "the"
academyawards["movie"].str.contains("the")

0     False
1     False
2      True
3     False
4     False
      ...
80    False
81    False
82    False
83    False
84    False
Name: movie, Length: 85, dtype: bool

### Funzioni utili

Oltre a queste funzionalità di indexing, possiamo usare `.head()` e `.tail()` per ottenere rispettivamente l'inizio e la fine del nostro DataFrame

In [65]:
academyawards.head()

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast
0,Wings,tt0018578,1927,1929,"William A. Wellman, Harry d’Abbadie d’Arrast",Paramount Pictures,12,5
1,The Broadway Melody,tt0019729,1929,1930,Harry Beaumont,Metro-Goldwyn-Mayer,4,3
2,All Quiet on the Western Front,tt0020629,1930,1930,"Lewis Milestone, Nate Watt",Universal Pictures,22,6
3,Cimarron,tt0021746,1931,1931,Wesley Ruggles,RKO Pictures,13,6
4,Grand Hotel,tt0022958,1932,1932,Edmund Goulding,Metro-Goldwyn-Mayer,19,8

In [66]:
academyawards.tail()

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast
80,Spotlight,tt1895587,2015,2016,Tom McCarthy,"Anonymous Content, Participant",15,2
81,Moonlight,tt4975722,2016,2017,Barry Jenkins,"Plan B Entertainment, A24",6,2
82,The Shape of Water,tt5580390,2017,2018,Guillermo del Toro,"Searchlight Pictures, TSG Entertainment",8,3
83,Green Book,tt6966692,2018,2019,Peter Farrelly,"Universal Pictures, DreamWorks, Participant, A...",7,1
84,Parasite,tt6751668,2019,2020,Bong Joon-ho,"CJ Entertainment, Barunson E&A",5,5

## Aggiungere righe e colonne

Per aggiungere una riga al DataFrame, possiamo semplicemente usare `loc` per inserire una riga con un indice che non è già presente nel DataFrame

**Attenzione: se abbiamo inserito indici diversi da quelli "sequenziali" dobbiamo usare quelli!**

In [67]:
academyawards.loc[len(academyawards)] = {"movie":"Nomadland",
                                         "imdb": "tt9770150",
                                         "year": 2020,
                                         "award_year": 2020,
                                        "directors": "Chloé Zhao",
                                         "companies": "Highwayman,Hear/Say Productions,Cor Cordium Productions"}

#what happened to the female, male, total cast?
academyawards.tail()

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast
81,Moonlight,tt4975722,2016,2017,Barry Jenkins,"Plan B Entertainment, A24",6.0,2.0
82,The Shape of Water,tt5580390,2017,2018,Guillermo del Toro,"Searchlight Pictures, TSG Entertainment",8.0,3.0
83,Green Book,tt6966692,2018,2019,Peter Farrelly,"Universal Pictures, DreamWorks, Participant, A...",7.0,1.0
84,Parasite,tt6751668,2019,2020,Bong Joon-ho,"CJ Entertainment, Barunson E&A",5.0,5.0
85,Nomadland,tt9770150,2020,2020,Chloé Zhao,"Highwayman,Hear/Say Productions,Cor Cordium Pr...",NaN,NaN

In [68]:
# if we specified different indices, we need to use those
ghibli_movies.loc[2001]={"title": "Spirited Away", 
                         "director": "Hayao Miyazaki", 
                         "saddest movie ever?": False}

In [69]:
ghibli_movies

                       title        director  saddest movie ever?
year
1997       Princess Mononoke  Hayao Miyazaki                False
1988  Grave of the Fireflies   Isao Takahata                 True
1992             Porco Rosso  Hayao Miyazaki                False
2006     Tales from Earthsea   Gorō Miyazaki                False
2001           Spirited Away  Hayao Miyazaki                False

Per aggiungere una colonna, invece, la aggiungiamo "indicizzando" il suo nome:

In [70]:
# add a column that indicates whether they won the oscar. For now, let's put "False" everywhere
ghibli_movies["won oscar"] = False

In [71]:
ghibli_movies

                       title        director  saddest movie ever?  won oscar
year
1997       Princess Mononoke  Hayao Miyazaki                False      False
1988  Grave of the Fireflies   Isao Takahata                 True      False
1992             Porco Rosso  Hayao Miyazaki                False      False
2006     Tales from Earthsea   Gorō Miyazaki                False      False
2001           Spirited Away  Hayao Miyazaki                False      False

Naturalmente, possiamo anche inserire dei valori che sono derivati da altre colonne:

In [72]:
academyawards["total_cast"] = academyawards["male_cast"] + academyawards["female_cast"]
academyawards.tail()

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast,total_cast
81,Moonlight,tt4975722,2016,2017,Barry Jenkins,"Plan B Entertainment, A24",6.0,2.0,8.0
82,The Shape of Water,tt5580390,2017,2018,Guillermo del Toro,"Searchlight Pictures, TSG Entertainment",8.0,3.0,11.0
83,Green Book,tt6966692,2018,2019,Peter Farrelly,"Universal Pictures, DreamWorks, Participant, A...",7.0,1.0,8.0
84,Parasite,tt6751668,2019,2020,Bong Joon-ho,"CJ Entertainment, Barunson E&A",5.0,5.0,10.0
85,Nomadland,tt9770150,2020,2020,Chloé Zhao,"Highwayman,Hear/Say Productions,Cor Cordium Pr...",NaN,NaN,NaN

## Quiz

1. Crea una nuova colonna `male_ratio` che corrisponde alla frazione di uomini sul totale di attori nel DataFrame `academyawards`
2. Salva la versione aggiornata della tabella degli oscar in `output/academyawards.csv`

In [ ]:
academyawards["male_ratio"] = academyawards["male_cast"] / academyawards["total_cast"]
academyawards.tail()

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast,total_cast,male_ratio
81,Moonlight,tt4975722,2016,2017,Barry Jenkins,"Plan B Entertainment, A24",6.0,2.0,8.0,0.750000
82,The Shape of Water,tt5580390,2017,2018,Guillermo del Toro,"Searchlight Pictures, TSG Entertainment",8.0,3.0,11.0,0.727273
83,Green Book,tt6966692,2018,2019,Peter Farrelly,"Universal Pictures, DreamWorks, Participant, A...",7.0,1.0,8.0,0.875000
84,Parasite,tt6751668,2019,2020,Bong Joon-ho,"CJ Entertainment, Barunson E&A",5.0,5.0,10.0,0.500000
85,Nomadland,tt9770150,2020,2020,Chloé Zhao,"Highwayman,Hear/Say Productions,Cor Cordium Pr...",NaN,NaN,NaN,NaN

In [76]:
# Es2
academyawards.to_csv("output/academyawards.csv")

## Statistiche

Per quanto riguarda le colonne che contengono valori numerici, Pandas ci offre delle funzionalità per calcolare valori statistici:

In [80]:
# the mean (average) number of male actors in movies
print(academyawards["male_cast"].mean())

16.858823529411765

In [83]:
# the maximum number of total actors in movies
print(academyawards["total_cast"].max())
academyawards[academyawards["total_cast"] == academyawards["total_cast"].max()]

118.0

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast,total_cast,male_ratio
59,Forrest Gump,tt0109830,1994,1995,Robert Zemeckis,Paramount Pictures,89.0,29.0,118.0,0.754237

In [82]:
# the minimum number of total actors in movies
print(academyawards["female_cast"].min())

1.0

In [84]:
# some fundamental statistics about the total number of actors
print(academyawards["total_cast"].describe())

#academyawards.tail()

count     85.000000
mean      22.694118
std       15.362310
min        7.000000
25%       14.000000
50%       19.000000
75%       27.000000
max      118.000000
Name: total_cast, dtype: float64

## Quiz

1. La nostra lista di Oscar si ferma al 2020. Inserisci nel DataFrame anche le righe per gli ultimi anni. Inserisci solo titolo, anno e director.
2. Selezionia da `academyawards` i film il cui cast femminile è più grande di quello maschile
3. Salva i film con maggioranza di cast femminile in un file excel (usa la funzione `to_excel`) e in un file json (usa `to_json`).

In [ ]:
# ES1
academyawards.loc[len(academyawards)] = {"movie":"CODA",
                                         "year": 2021,
                                         "award_year": 2021,
                                        "directors": "boh"}

In [92]:
#ES2
more_females = academyawards[academyawards["female_cast"] > academyawards["male_cast"]]
more_females

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast,total_cast,male_ratio
22,An American in Paris,tt0043278,1951,1952,Vincente Minnelli,Metro-Goldwyn-Mayer,5.0,6.0,11.0,0.454545
34,The Sound of Music,tt0059742,1965,1966,Robert Wise,20th Century Studios,7.0,14.0,21.0,0.333333
67,Chicago,tt0299658,2002,2003,Rob Marshall,Miramax,5.0,8.0,13.0,0.384615

In [89]:
more_females.to_csv("output/more_females.csv")

In [90]:
more_females.to_json("output/more_females.json")