# Pandas - Parte 2

Nelle lezioni precedenti abbiamo visto le funzionalità di base di Pandas. Oggi vediamo alcune funzionalità più avanzate, fra cui quelle che ci permettono di combinare i contenuti di più DataFrame in uno.

Prima di partire, come al solito, importiamo pandas:

In [1]:
import pandas as pd

## Chained indexing

Ricominciamo da dove eravamo rimasti, con il nostro DataFrame di film dello studio Ghibli, con la colonna "won oscar" che conteneva un errore:

In [2]:
ghibli_movies = pd.DataFrame({
    "title" : ["Princess Mononoke", "Grave of the Fireflies", "Porco Rosso", 
               "Tales from Earthsea", "Spirited Away"],
    "director" : ["Hayao Miyazaki", "Isao Takahata", "Hayao Miyazaki", "Gorō Miyazaki", "Hayao Miyazaki"],
    "saddest movie ever?" : [False, True, False, False, False],
    "year": [1997, 1988, 1992, 2006, 2001],
    "won oscar": [False, False, False, False, False]
    },
    index = [1997, 1988, 1992, 2006, 2001]
)

ghibli_movies

,title,director,saddest movie ever?,year,won oscar
1997,Princess Mononoke,Hayao Miyazaki,False,1997,False
1988,Grave of the Fireflies,Isao Takahata,True,1988,False
1992,Porco Rosso,Hayao Miyazaki,False,1992,False
2006,Tales from Earthsea,Gorō Miyazaki,False,2006,False
2001,Spirited Away,Hayao Miyazaki,False,2001,False

Proviamo ad assegnare la colonna "won oscar" con il valore corretto:

In [3]:
ghibli_movies[ghibli_movies["title"]=="Spirited Away"]["won oscar"] = True

ghibli_movies

/tmp/ipykernel_5583/2481038265.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  ghibli_movies[ghibli_movies["title"]=="Spirited Away"]["won oscar"] = True

,title,director,saddest movie ever?,year,won oscar
1997,Princess Mononoke,Hayao Miyazaki,False,1997,False
1988,Grave of the Fireflies,Isao Takahata,True,1988,False
1992,Porco Rosso,Hayao Miyazaki,False,1992,False
2006,Tales from Earthsea,Gorō Miyazaki,False,2006,False
2001,Spirited Away,Hayao Miyazaki,False,2001,False

In [4]:
spirited_away = ghibli_movies[ghibli_movies["title"]=="Spirited Away"]

spirited_away["won oscar"] = True

print("===SPIRITED AWAY===")
print(spirited_away)
print("===ALL MOVIES===")
print(ghibli_movies)

===SPIRITED AWAY===
              title        director  saddest movie ever?  year  won oscar
2001  Spirited Away  Hayao Miyazaki                False  2001       True
===ALL MOVIES===
                       title        director  saddest movie ever?  year  \
1997       Princess Mononoke  Hayao Miyazaki                False  1997
1988  Grave of the Fireflies   Isao Takahata                 True  1988
1992             Porco Rosso  Hayao Miyazaki                False  1992
2006     Tales from Earthsea   Gorō Miyazaki                False  2006
2001           Spirited Away  Hayao Miyazaki                False  2001

      won oscar
1997      False
1988      False
1992      False
2006      False
2001      False

Cerchiamo di capire questo errore: abbiamo fatto quello che si chiama *chained indexing*. Infatti se notate abbiamo usato due metodi di indicizzazione per il nostro DataFrame: prima chiediamo le righe dove il titolo è == a "Spirited Away", poi indicizziamo la colonna "won oscar". Questo crea **una copia** del nostro DataFrame, e infatti non abbiamo modificato l'originale!

Per risolvere questo problema, possiamo usare `.loc` quando vogliamo riassegnare un valore del DataFrame

In [5]:
ghibli_movies.loc[2001, "won oscar"] = True

ghibli_movies

,title,director,saddest movie ever?,year,won oscar
1997,Princess Mononoke,Hayao Miyazaki,False,1997,False
1988,Grave of the Fireflies,Isao Takahata,True,1988,False
1992,Porco Rosso,Hayao Miyazaki,False,1992,False
2006,Tales from Earthsea,Gorō Miyazaki,False,2006,False
2001,Spirited Away,Hayao Miyazaki,False,2001,True

Oppure possiamo usare `.at`

In [6]:
ghibli_movies["won oscar"] = False
ghibli_movies.at[2001, "won oscar"] = True

ghibli_movies

,title,director,saddest movie ever?,year,won oscar
1997,Princess Mononoke,Hayao Miyazaki,False,1997,False
1988,Grave of the Fireflies,Isao Takahata,True,1988,False
1992,Porco Rosso,Hayao Miyazaki,False,1992,False
2006,Tales from Earthsea,Gorō Miyazaki,False,2006,False
2001,Spirited Away,Hayao Miyazaki,False,2001,True

## Sorting

Una delle operazioni che non abbiamo ancora discusso è quella di **ordinamento** (*sorting*) dei DataFrame. Possiamo infatti riordinare gli assi del nostro DataFrame usando il metodo `.sort_values`.

In [21]:
ghibli_movies = pd.DataFrame({
    "title" : ["Princess Mononoke", "Grave of the Fireflies", "Porco Rosso", "Tales from Earthsea", "Spirited Away"],
    "director" : ["Hayao Miyazaki", "Isao Takahata", "Hayao Miyazaki", "Gorō Miyazaki", "Hayao Miyazaki"],
    "saddest movie ever?" : [False, True, False, False, False],
    "year": [1997, 1988, 1992, 2006, 2001],
    "won oscar": [False, False, False, False, True]
    }
)
ghibli_movies

,title,director,saddest movie ever?,year,won oscar
0,Princess Mononoke,Hayao Miyazaki,False,1997,False
1,Grave of the Fireflies,Isao Takahata,True,1988,False
2,Porco Rosso,Hayao Miyazaki,False,1992,False
3,Tales from Earthsea,Gorō Miyazaki,False,2006,False
4,Spirited Away,Hayao Miyazaki,False,2001,True

In [8]:
ghibli_movies.sort_values("year")

,title,director,saddest movie ever?,year,won oscar
1,Grave of the Fireflies,Isao Takahata,True,1988,False
2,Porco Rosso,Hayao Miyazaki,False,1992,False
0,Princess Mononoke,Hayao Miyazaki,False,1997,False
4,Spirited Away,Hayao Miyazaki,False,2001,True
3,Tales from Earthsea,Gorō Miyazaki,False,2006,False

Attenzione però: la variabile originale `ghibli_movies` non è stata modificata

In [9]:
ghibli_movies

,title,director,saddest movie ever?,year,won oscar
0,Princess Mononoke,Hayao Miyazaki,False,1997,False
1,Grave of the Fireflies,Isao Takahata,True,1988,False
2,Porco Rosso,Hayao Miyazaki,False,1992,False
3,Tales from Earthsea,Gorō Miyazaki,False,2006,False
4,Spirited Away,Hayao Miyazaki,False,2001,True

Per applicare i cambiamenti alla nostra variabile, usiamo il parametro opzionale `inplace`:

In [10]:
ghibli_movies.sort_values("year", inplace=True)
ghibli_movies

,title,director,saddest movie ever?,year,won oscar
1,Grave of the Fireflies,Isao Takahata,True,1988,False
2,Porco Rosso,Hayao Miyazaki,False,1992,False
0,Princess Mononoke,Hayao Miyazaki,False,1997,False
4,Spirited Away,Hayao Miyazaki,False,2001,True
3,Tales from Earthsea,Gorō Miyazaki,False,2006,False

In [ ]:
def optional_arguments(non_optional, optional=False, optional2=0):
    print(f"non optional is {non_optional}")
    print(f"optional is {optional}")
    print(f"optional2 is {optional2}")


optional_arguments(42, optional2=-1)

non optional is 42
optional is False
optional2 is -1

**Oppure** riassegnamo la variabile:

In [18]:
ghibli_movies = ghibli_movies.sort_values("year")
ghibli_movies

,title,director,saddest movie ever?,year,won oscar
1,Grave of the Fireflies,Isao Takahata,True,1988,False
2,Porco Rosso,Hayao Miyazaki,False,1992,False
0,Princess Mononoke,Hayao Miyazaki,False,1997,False
4,Spirited Away,Hayao Miyazaki,False,2001,True
3,Tales from Earthsea,Gorō Miyazaki,False,2006,False

A questo punto però abbiamo "incasinato" gli indici del nostro DataFrame. Per evitare questa situazione, possiamo usare `ignore_index` quando facciamo `sort`:

In [23]:
ghibli_movies = ghibli_movies.sort_values("year", ignore_index=True)
ghibli_movies

,title,director,saddest movie ever?,year,won oscar
0,Grave of the Fireflies,Isao Takahata,True,1988,False
1,Porco Rosso,Hayao Miyazaki,False,1992,False
2,Princess Mononoke,Hayao Miyazaki,False,1997,False
3,Spirited Away,Hayao Miyazaki,False,2001,True
4,Tales from Earthsea,Gorō Miyazaki,False,2006,False

In [22]:
ghibli_movies_titles = ghibli_movies["title"]
ghibli_movies_sorted = ghibli_movies.sort_values("year", ignore_index=True)
ghibli_movies_sorted["title"] = ghibli_movies_titles
ghibli_movies_sorted

,title,director,saddest movie ever?,year,won oscar
0,Princess Mononoke,Isao Takahata,True,1988,False
1,Grave of the Fireflies,Hayao Miyazaki,False,1992,False
2,Porco Rosso,Hayao Miyazaki,False,1997,False
3,Tales from Earthsea,Hayao Miyazaki,False,2001,True
4,Spirited Away,Gorō Miyazaki,False,2006,False

## Una breve nota su `index`

Quando salviamo file usando Pandas, la libreria inserisce anche gli indici come colonna. Vediamo subito il risultato in un file CSV:

In [24]:
ghibli_movies.to_csv("output/ghibli.csv")

Se non vogliamo includere gli indici, possiamo usare il parametro opzionale `index`:

In [25]:
ghibli_movies.to_csv("output/ghibli.csv", index=False)

In [26]:
ghibli_movies = pd.read_csv("output/ghibli.csv")
ghibli_movies

,title,director,saddest movie ever?,year,won oscar
0,Grave of the Fireflies,Isao Takahata,True,1988,False
1,Porco Rosso,Hayao Miyazaki,False,1992,False
2,Princess Mononoke,Hayao Miyazaki,False,1997,False
3,Spirited Away,Hayao Miyazaki,False,2001,True
4,Tales from Earthsea,Gorō Miyazaki,False,2006,False

## Quiz

1. Una persona malvagia ha messo in disordine il file che contiene tutte le informazioni sugli Oscar! Aprilo (in `data/academyawards_mess.csv`) usando Pandas e riordina le righe usando `award_year`. Salva il file in formato CSV in `outputs/academyawards_fixed.csv` non inserendo gli indici.

In [32]:
academyawards = pd.read_csv("data/academyawards_mess.csv")
academyawards.sort_values("award_year", inplace=True)
academyawards.to_csv("output/academyawards_fixed.csv", index=False)
academyawards.head()

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast
36,Wings,tt0018578,1927,1929,"William A. Wellman, Harry d’Abbadie d’Arrast",Paramount Pictures,12,5
3,The Broadway Melody,tt0019729,1929,1930,Harry Beaumont,Metro-Goldwyn-Mayer,4,3
55,All Quiet on the Western Front,tt0020629,1930,1930,"Lewis Milestone, Nate Watt",Universal Pictures,22,6
46,Cimarron,tt0021746,1931,1931,Wesley Ruggles,RKO Pictures,13,6
0,Grand Hotel,tt0022958,1932,1932,Edmund Goulding,Metro-Goldwyn-Mayer,19,8

# Liste dentro alle celle

Oltre a strutture puramente bidimensionali, Pandas ci consente anche di creare strutture più complesse (annidate). Ce ne sarebbero molti tipi, ma noi vediamo solo una versione, quella in cui creiamo una lista all'interno di una cella del DataFrame. Per farlo, usiamo il metodo "split" su stringhe, che divide una stringa usando un separatore

In [33]:
academyawards = pd.read_csv("data/academyawards.csv")

academyawards["directors"] = academyawards["directors"].str.split(",")
academyawards

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast
0,Wings,tt0018578,1927,1929,"[William A. Wellman, Harry d’Abbadie d’Arrast]",Paramount Pictures,12,5
1,The Broadway Melody,tt0019729,1929,1930,[Harry Beaumont],Metro-Goldwyn-Mayer,4,3
2,All Quiet on the Western Front,tt0020629,1930,1930,"[Lewis Milestone, Nate Watt]",Universal Pictures,22,6
3,Cimarron,tt0021746,1931,1931,[Wesley Ruggles],RKO Pictures,13,6
4,Grand Hotel,tt0022958,1932,1932,[Edmund Goulding],Metro-Goldwyn-Mayer,19,8
...,...,...,...,...,...,...,...,...
80,Spotlight,tt1895587,2015,2016,[Tom McCarthy],"Anonymous Content, Participant",15,2
81,Moonlight,tt4975722,2016,2017,[Barry Jenkins],"Plan B Entertainment, A24",6,2
82,The Shape of Water,tt5580390,2017,2018,[Guillermo del Toro],"Searchlight Pictures, TSG Entertainment",8,3
83,Green Book,tt6966692,2018,2019,[Peter Farrelly],"Universal Pictures, DreamWorks, Participant, A...",7,1
84,Parasite,tt6751668,2019,2020,[Bong Joon-ho],"CJ Entertainment, Barunson E&A",5,5

Per accedere all'ennesimo elemento di queste liste scriviamo:

In [34]:
academyawards.loc[0,"directors"][0]

'William A. Wellman'

Possiamo assegnare una lista a una cella usando `.at`, `.loc` non funziona!

In [35]:
# this does not work
academyawards.loc[0,"directors"] = ["Some", "Directors"]

ValueError: Must have equal len keys and value when setting with an iterable

In [36]:
academyawards.at[0,"directors"] = ["Some", "Directors"]
academyawards.head()

,movie,imdb,year,award_year,directors,companies,male_cast,female_cast
0,Wings,tt0018578,1927,1929,"[Some, Directors]",Paramount Pictures,12,5
1,The Broadway Melody,tt0019729,1929,1930,[Harry Beaumont],Metro-Goldwyn-Mayer,4,3
2,All Quiet on the Western Front,tt0020629,1930,1930,"[Lewis Milestone, Nate Watt]",Universal Pictures,22,6
3,Cimarron,tt0021746,1931,1931,[Wesley Ruggles],RKO Pictures,13,6
4,Grand Hotel,tt0022958,1932,1932,[Edmund Goulding],Metro-Goldwyn-Mayer,19,8

# groupby

Un altro metodo utile di Pandas è groupby. Questo metodo ci consente di "raggruppare" il DataFrame usando i valori di una colonna specifica. Vediamo un esempio:

In [37]:
animals = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})
animals.groupby("Animal")

`groupby` ha ora raggruppato le righe tramite i valori della colonna `Animal`. Tuttavia, non possiamo ancora usare questo risultato. Dobbiamo invece usare un metodo per dire a Pandas come aggregare i valori (in questo caso le velocità medie)

In [38]:
animals.groupby("Animal").mean()

        Max Speed
Animal
Falcon      375.0
Parrot       25.0

Possiamo anche contare quante volte appare ciascun animale!

In [39]:
animals.groupby("Animal").count()

        Max Speed
Animal
Falcon          2
Parrot          2

Cosa succede se abbiamo anche colonne con valori non numerici?

In [ ]:
meteo_bolo = pd.read_csv("data/meteo_bologna.csv")
meteo_bolo

,Data,Temperatura media,Temperatura massima,Temperatura minima,Stagione,Precipitazioni (mm)
0,2001-01-05,3.7,6.3,1.4,Inverno,0.1
1,2001-01-08,7.1,9.5,3.9,Inverno,6.2
2,2001-01-09,8.9,14.0,5.6,Inverno,0.3
3,2001-01-10,8.1,12.5,5.2,Inverno,0.1
4,2001-01-17,0.1,1.8,-1.3,Inverno,1.2
...,...,...,...,...,...,...
8850,2003-09-16,18.7,26.0,12.6,Estate,0.0
8851,2003-09-17,19.8,27.4,13.7,Estate,0.0
8852,2003-09-21,22.4,30.2,16.3,Estate,0.0
8853,2003-09-22,22.7,29.8,15.7,Estate,0.0
8854,2003-09-26,15.4,22.1,10.4,Autunno,0.0

In [43]:
# it doesn't work! the column data contains strings, 
# it does not support mean
meteo_bolo.groupby("Stagione").mean()

TypeError: dtype 'str' does not support operation 'mean'

Dobbiamo filtrare e usare solo le colonne che ci servono!

In [44]:
meteo_bolo_stagioni = meteo_bolo[["Stagione", "Precipitazioni (mm)",
                                  "Temperatura media"]]
meteo_bolo_stagioni.groupby("Stagione").mean()

           Precipitazioni (mm)  Temperatura media
Stagione
Autunno               2.596114          11.373221
Estate                1.472473          24.527704
Inverno               1.902717           5.884944
Primavera             2.412218          17.085347

## concat

Oltre alla possibilità di aggiungere righe e colonne, Pandas offre una serie di metodi per combinare più DataFrame in uno. Il primo è `concat`, che concatena le righe di un DataFrame ad un altro.

In [45]:
ghibli_1 = pd.DataFrame({
    "title": ["Princess Mononoke", "Grave of the Fireflies"],
    "director" : ["Hayao Miyazaki", "Isao Takahata"],
    "year": [1997, 1988]
})

ghibli_2 = pd.DataFrame({
    "title": ["Porco Rosso", "Tales from Earthsea"],
    "director": ["Hayao Miyazaki", "Gorō Miyazaki"],
    "year": [1992, 2006]
})

ghibli_movies = pd.concat((ghibli_1, ghibli_2))
ghibli_movies

                    title        director  year
0       Princess Mononoke  Hayao Miyazaki  1997
1  Grave of the Fireflies   Isao Takahata  1988
0             Porco Rosso  Hayao Miyazaki  1992
1     Tales from Earthsea   Gorō Miyazaki  2006

In [48]:
ghibli_movies.loc[0]

               title        director  year
0  Princess Mononoke  Hayao Miyazaki  1997
0        Porco Rosso  Hayao Miyazaki  1992

Se vogliamo risistemare gli indici usiamo `ignore_index`:

In [49]:
ghibli_movies = pd.concat((ghibli_1, ghibli_2), ignore_index=True)
ghibli_movies

                    title        director  year
0       Princess Mononoke  Hayao Miyazaki  1997
1  Grave of the Fireflies   Isao Takahata  1988
2             Porco Rosso  Hayao Miyazaki  1992
3     Tales from Earthsea   Gorō Miyazaki  2006

Cosa succede se abbiamo colonne in una tabella ma nell'altra non ci sono?

In [50]:
ghibli_1["won oscar"]=False
ghibli_1

                    title        director  year  won oscar
0       Princess Mononoke  Hayao Miyazaki  1997      False
1  Grave of the Fireflies   Isao Takahata  1988      False

In [51]:

ghibli_movies = pd.concat((ghibli_1, ghibli_2), ignore_index=True)
ghibli_movies

                    title        director  year won oscar
0       Princess Mononoke  Hayao Miyazaki  1997     False
1  Grave of the Fireflies   Isao Takahata  1988     False
2             Porco Rosso  Hayao Miyazaki  1992       NaN
3     Tales from Earthsea   Gorō Miyazaki  2006       NaN

In [52]:
ghibli_1["bello"] = "bello"
pd.concat((ghibli_1, ghibli_2), ignore_index=True)

                    title        director  year won oscar  bello
0       Princess Mononoke  Hayao Miyazaki  1997     False  bello
1  Grave of the Fireflies   Isao Takahata  1988     False  bello
2             Porco Rosso  Hayao Miyazaki  1992       NaN    NaN
3     Tales from Earthsea   Gorō Miyazaki  2006       NaN    NaN

## join


Un'altra posssibilità è quella di voler unire le colonne di due DataFrame. Lo si fa con `join`

In [56]:
names = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda"], 
                      "surnames": ["Esposito", "Testa", "Barbieri", "Gallo"]})
ages = pd.DataFrame({"ages": [64, 30, 43, 88]})

names.join(ages)

     names  surnames  ages
0   Andrea  Esposito    64
1  Claudia     Testa    30
2    Piero  Barbieri    43
3  Mafalda     Gallo    88

Cosa succede se la stessa colonna appare più volte?

In [57]:
names = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda"],
                      "surnames": ["Esposito", "Testa", "Barbieri", "Gallo"]})
ages = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda"], 
                     "ages": [64, 30, 43, 88]})
names.join(ages)

ValueError: columns overlap but no suffix specified: Index(['names'], dtype='str')

Non possiamo farlo! Le colonne avrebbero lo stesso nome! Se vogliamo fare `join` dobbiamo specificare un suffisso per una o entrambe le colonne

In [58]:
names = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda"], 
                      "surnames": ["Esposito", "Testa", "Barbieri", "Gallo"]})
ages = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda"], 
                     "ages": [64, 30, 43, 88]})
names.join(ages, lsuffix="-left", rsuffix="-right")

  names-left  surnames names-right  ages
0     Andrea  Esposito      Andrea    64
1    Claudia     Testa     Claudia    30
2      Piero  Barbieri       Piero    43
3    Mafalda     Gallo     Mafalda    88

## merge

Infine, possiamo "unire" due DataFrame. In questo caso, il sistema controllerà dove le colonne che sono presenti in entrambi i DataFrame hanno lo stesso valore, unendo le que righe corrispondenti:

In [ ]:
names = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda"], 
                      "surnames": ["Esposito", "Testa", "Barbieri", "Gallo"]})
ages = pd.DataFrame({"names": ["Claudia", "Piero", "Mafalda", "Andrea"], 
                     "ages": [64, 30, 43, 88]})
pd.merge(names, ages)

     names  surnames  ages
0  Claudia     Testa    64
1    Piero  Barbieri    30
2  Mafalda     Gallo    43

In [61]:
# what happens when there are rows on one side and not the other?
names = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", 
                                "Mafalda", "Giovanni"], 
                      "surnames": ["Esposito", "Testa", "Barbieri", 
                                   "Gallo", "Serra"]})
ages = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", 
                               "Mafalda", "Antonio"], 
                     "ages": [64, 30, 43, 88, 24]})
pd.merge(names, ages)

     names  surnames  ages
0   Andrea  Esposito    64
1  Claudia     Testa    30
2    Piero  Barbieri    43
3  Mafalda     Gallo    88

In [62]:
# or i could do an outer merge
names = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda", "Giovanni"], 
                      "surnames": ["Esposito", "Testa", "Barbieri", "Gallo", "Serra"]})
ages = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda", "Antonio"], 
                     "ages": [64, 30, 43, 88, 24]})
                     
pd.merge(names, ages, how="outer")

      names  surnames  ages
0    Andrea  Esposito  64.0
1   Antonio       NaN  24.0
2   Claudia     Testa  30.0
3  Giovanni     Serra   NaN
4   Mafalda     Gallo  88.0
5     Piero  Barbieri  43.0

In [64]:
# or i could do an outer merge
names = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda", "Giovanni"], 
                      "surnames": ["Esposito", "Testa", "Barbieri", "Gallo", "Serra"]})
ages = pd.DataFrame({"names": ["Andrea", "Claudia", "Piero", "Mafalda", "Antonio"], 
                     "ages": [64, 30, 43, 88, 24]})
                     
pd.merge(names, ages, how="right")

     names  surnames  ages
0   Andrea  Esposito    64
1  Claudia     Testa    30
2    Piero  Barbieri    43
3  Mafalda     Gallo    88
4  Antonio       NaN    24

## Quiz

1. Scarica i dati di temperatura e precipitazioni (disaggregati) da [qui](https://opendata.comune.bologna.it/explore/?sort=modified&refine.theme=Ambiente). Unisci i due file CSV usando Pandas.

In [ ]:
# CAUTION: use semicolon (;) as separator
temperature = pd.read_csv("data/temperature_bologna.csv", sep=";")
precipitazioni = pd.read_csv("data/precipitazioni_bologna.csv", sep=";")

pd.merge(temperature, precipitazioni)

,Data,Temperatura media,Temperatura massima,Temperatura minima,Stagione,Precipitazioni (mm)
0,2003-10-03,21.5,28.2,16.2,Autunno,0.0
1,2003-10-04,21.6,27.2,15.9,Autunno,1.9
2,2003-10-09,17.1,24.1,10.8,Autunno,0.0
3,2003-10-10,16.8,24.3,11.2,Autunno,0.0
4,2003-10-11,18.6,24.5,12.9,Autunno,0.0
...,...,...,...,...,...,...
9242,2026-04-05,15.5,23.0,8.1,Primavera,0.0
9243,2026-04-08,16.5,23.0,10.7,Primavera,0.0
9244,2026-04-12,13.8,15.8,10.2,Primavera,0.6
9245,2026-04-17,17.8,24.3,12.0,Primavera,0.0
9246,2026-04-18,18.5,24.8,12.2,Primavera,0.0