# Esercizi

1. Il file `data/meteo_bologna.csv` contiene precipitazioni e temperature giornaliere per Bologna. Leggilo usando Pandas. Stampa l'inizio del file per vederne la struttura.

In [30]:
import pandas as pd

# ES1
meteo = pd.read_csv("data/meteo_bologna.csv")
meteo.tail()

,Data,Temperatura media,Temperatura massima,Temperatura minima,Stagione,Precipitazioni (mm)
8850,2003-09-16,18.7,26.0,12.6,Estate,0.0
8851,2003-09-17,19.8,27.4,13.7,Estate,0.0
8852,2003-09-21,22.4,30.2,16.3,Estate,0.0
8853,2003-09-22,22.7,29.8,15.7,Estate,0.0
8854,2003-09-26,15.4,22.1,10.4,Autunno,0.0

2. Stampa la data in cui sono avvenute le temperature minime e massime.

In [ ]:
# ES2
temp_minima = meteo["Temperatura minima"].min()
df_temp_minima = meteo[ meteo["Temperatura minima"] == temp_minima]
df_temp_minima["Data"]

'2001-01-05'

In [ ]:
# Usando sort
meteo.sort_values("Temperatura minima").loc[0, "Data"]

3. Calcola le precipitazioni medie giornaliere.

In [14]:
# ES3
meteo["Precipitazioni (mm)"].describe()

count    8855.000000
mean        2.087984
std         6.201226
min         0.000000
25%         0.000000
50%         0.000000
75%         0.600000
max       121.600000
Name: Precipitazioni (mm), dtype: float64

4. Calcola le temperature minime medie giornaliere per estate, inverno, autunno, primavera (usa un ciclo for e indicizzazione avanzata).

In [21]:
# ES4
stagioni = ["Inverno", "Autunno", "Primavera", "Estate"]
for stagione in stagioni:
    temperature_minime_stagione = meteo[meteo["Stagione"] == stagione]
    t_media = temperature_minime_stagione["Temperatura minima"].mean()
    print(f"in {stagione} la temperatura minima media è {t_media}")

in Inverno la temperatura minima media è 2.464365256124722
in Autunno la temperatura minima media è 8.099250936329588
in Primavera la temperatura minima media è 11.958431018935977
in Estate la temperatura minima media è 18.864760638297874

5. Calcola le precipitazioni medie giornaliere per estate, inverno, autunno, primavera (usa groupby).

In [26]:
# ES5
meteo[["Stagione","Precipitazioni (mm)"]].groupby("Stagione").mean()

           Precipitazioni (mm)
Stagione
Autunno               2.596114
Estate                1.472473
Inverno               1.902717
Primavera             2.412218

6. Quali sono stati i tre giorni di fila con più pioggia? SUGGERIMENTO: puoi usare un ciclo for, iloc e slicing per creare una lista con le precipitazioni cumulative.

In [42]:
# ES6
max_precipitazione = -1
max_idx = -1
for idx in range(len(meteo)):
    three_day_precipitation = meteo.iloc[idx:idx+3]["Precipitazioni (mm)"]
    if three_day_precipitation.sum() > max_precipitazione:
        max_precipitazione = three_day_precipitation.sum()
        max_idx = idx

print(f"la prec massima è {max_precipitazione}")
print(f"la data è {meteo.iloc[max_idx]["Data"]}")

la prec massima è 127.69999999999999
la data è 2024-10-08

In [48]:
# con una lista
precipitazioni_3gg = []
for idx in range(len(meteo)):
    three_day_precipitation = meteo.iloc[idx:idx+3]["Precipitazioni (mm)"]
    precipitazioni_3gg.append(three_day_precipitation.sum())

print(precipitazioni_3gg)
meteo["Precipitazioni 3gg"] = precipitazioni_3gg
meteo.sort_values("Precipitazioni 3gg", ascending=False).iloc[0]

[np.float64(6.6), np.float64(6.6), np.float64(1.6), np.float64(1.3), np.float64(1.2), np.float64(0.0), np.float64(0.0), np.float64(0.7), np.float64(22.7), np.float64(22.7), np.float64(22.0), np.float64(0.4), np.float64(0.4), np.float64(0.4), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(10.1), np.float64(10.1), np.float64(10.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(3.5), np.float64(3.5), np.float64(3.5), np.float64(3.6), np.float64(3.6), np.float64(3.6), np.float64(0.2), np.float64(0.30000000000000004), np.float64(0.30000000000000004), np.float64(0.1), np.float64(0.8), np.float64(5.2), np.float64(36.5), np.float64(36.2), np.float64(31.8), np.float64(0.6), np.float64(2.3000000000000003), np.float64(2.3000000000000003), np.float64(2.2), np.float64(15.0), np.float64(15.6), np.float64(15.6), np.float64(0.6), np.float64(0.0), np.float64(13.7), np.float64(13.7), np.float64(13.7), np.float64(0.0), np.float64(0.0), np.float64(3.2), np.float64(3.2), np.float64(3.2), np.float64(3.4), np.float64(3.4), np.float64(3.4), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(0.1), np.float64(18.5), np.float64(34.5), np.float64(34.5), np.float64(37.3), np.float64(21.2), np.float64(21.2), np.float64(0.0), np.float64(0.0), np.float64(38.0), np.float64(38.0), np.float64(38.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(14.0), np.float64(14.0), np.float64(14.0), np.float64(8.8), np.float64(8.8), np.float64(8.8), np.float64(0.0), np.float64(0.4), np.float64(0.4), np.float64(0.4), np.float64(0.0), np.float64(10.0), np.float64(20.8), np.float64(27.1), np.float64(17.1), np.float64(6.3), np.float64(0.0), np.float64(0.1), np.float64(7.699999999999999), np.float64(21.1), np.float64(23.9), np.float64(25.8), np.float64(12.4), np.float64(9.5), np.float64(4.5), np.float64(4.6), np.float64(4.699999999999999), np.float64(0.2), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0), np.float64(1.9), np.float64(4.199999999999999), np.float64(4.199999999999999), np.float64(2.3), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(12.7), np.float64(13.299999999999999), np.float64(13.299999999999999), np.float64(0.6), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0), np.float64(18.9), np.float64(22.9), np.float64(22.9), np.float64(4.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.9), np.float64(1.0), np.float64(20.7), np.float64(21.5), np.float64(21.4), np.float64(1.7), np.float64(0.0), np.float64(0.0), np.float64(4.0), np.float64(6.2), np.float64(10.9), np.float64(6.9), np.float64(4.7), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.0), np.float64(18.7), np.float64(32.0), np.float64(32.7), np.float64(14.0), np.float64(0.8999999999999999), np.float64(0.2), np.float64(0.2), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(8.5), np.float64(9.1), np.float64(14.1), np.float64(5.6), np.float64(24.6), np.float64(19.6), np.float64(19.6), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(6.4), np.float64(6.800000000000001), np.float64(6.800000000000001), np.float64(0.4), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(5.6), np.float64(5.6), np.float64(7.1), np.float64(21.1), np.float64(21.1), np.float64(33.0), np.float64(13.4), np.float64(13.4), np.float64(0.0), np.float64(39.1), np.float64(39.5), np.float64(45.4), np.float64(18.200000000000003), np.float64(17.8), np.float64(11.9), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(5.6), np.float64(5.6), np.float64(5.6), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(31.2), np.float64(33.0), np.float64(35.0), np.float64(3.8), np.float64(2.0), np.float64(4.6), np.float64(7.3999999999999995), np.float64(20.0), np.float64(41.8), np.float64(39.2), np.float64(31.9), np.float64(15.5), np.float64(15.3), np.float64(15.7), np.float64(5.8), np.float64(5.8), np.float64(0.1), np.float64(0.6), np.float64(13.0), np.float64(19.1), np.float64(19.3), np.float64(6.8999999999999995), np.float64(0.8), np.float64(0.0), np.float64(0.0), np.float64(0.4), np.float64(1.3), np.float64(1.3), np.float64(0.9), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(35.4), np.float64(35.4), np.float64(35.4), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(4.1), np.float64(4.1), np.float64(4.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(58.6), np.float64(60.5), np.float64(60.5), np.float64(6.1), np.float64(4.8), np.float64(4.8), np.float64(18.400000000000002), np.float64(17.8), np.float64(17.8), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.2), np.float64(0.7), np.float64(0.7), np.float64(0.5), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.7), np.float64(0.7), np.float64(0.7), np.float64(1.8), np.float64(3.5), np.float64(3.5), np.float64(3.0999999999999996), np.float64(1.4), np.float64(1.4), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.6), np.float64(1.2), np.float64(4.1), np.float64(3.5), np.float64(2.9), np.float64(0.2), np.float64(0.2), np.float64(6.2), np.float64(6.0), np.float64(6.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(0.30000000000000004), np.float64(0.30000000000000004), np.float64(0.2), np.float64(0.1), np.float64(0.1), np.float64(0.4), np.float64(0.3), np.float64(0.3), np.float64(28.6), np.float64(35.5), np.float64(35.5), np.float64(6.9), np.float64(0.0), np.float64(0.0), np.float64(3.4), np.float64(11.1), np.float64(11.2), np.float64(7.8), np.float64(1.5), np.float64(1.4), np.float64(2.5999999999999996), np.float64(1.2), np.float64(27.3), np.float64(27.400000000000002), np.float64(27.400000000000002), np.float64(3.8), np.float64(2.5), np.float64(4.2), np.float64(22.0), np.float64(22.0), np.float64(20.3), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.2), np.float64(0.30000000000000004), np.float64(44.199999999999996), np.float64(45.7), np.float64(45.7), np.float64(1.9000000000000001), np.float64(0.2), np.float64(0.1), np.float64(3.7), np.float64(3.7), np.float64(3.7), np.float64(0.0), np.float64(0.0), np.float64(0.2), np.float64(4.3), np.float64(4.5), np.float64(4.5), np.float64(0.4), np.float64(0.2), np.float64(0.0), np.float64(0.6), np.float64(0.6), np.float64(0.6), np.float64(2.7), np.float64(4.300000000000001), np.float64(4.300000000000001), np.float64(1.6), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.9), np.float64(4.9), np.float64(19.1), np.float64(32.5), np.float64(35.5), np.float64(21.7), np.float64(7.4), np.float64(0.4), np.float64(0.0), np.float64(2.3), np.float64(2.3), np.float64(2.3), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(19.6), np.float64(34.0), np.float64(35.1), np.float64(17.3), np.float64(19.4), np.float64(17.3), np.float64(17.5), np.float64(1.0), np.float64(5.6), np.float64(10.1), np.float64(11.2), np.float64(7.3999999999999995), np.float64(1.9000000000000001), np.float64(0.8), np.float64(0.2), np.float64(4.3), np.float64(5.3), np.float64(5.1), np.float64(1.0), np.float64(0.0), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.7), np.float64(1.7), np.float64(1.7), np.float64(3.6), np.float64(3.6), np.float64(3.6), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(11.0), np.float64(11.0), np.float64(11.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.8), np.float64(2.8), np.float64(3.0999999999999996), np.float64(0.4), np.float64(6.6000000000000005), np.float64(6.7), np.float64(51.5), np.float64(47.5), np.float64(47.1), np.float64(7.2), np.float64(43.4), np.float64(51.5), np.float64(48.0), np.float64(9.6), np.float64(1.5), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(6.4), np.float64(13.9), np.float64(14.0), np.float64(7.6), np.float64(0.1), np.float64(2.9), np.float64(22.299999999999997), np.float64(22.4), np.float64(19.5), np.float64(0.2), np.float64(0.1), np.float64(1.4000000000000001), np.float64(1.3), np.float64(1.3), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(12.1), np.float64(18.9), np.float64(19.299999999999997), np.float64(7.8), np.float64(1.9), np.float64(3.3), np.float64(2.7), np.float64(1.8), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.6), np.float64(3.3000000000000003), np.float64(3.3000000000000003), np.float64(2.7), np.float64(0.1), np.float64(25.8), np.float64(28.2), np.float64(28.099999999999998), np.float64(17.5), np.float64(17.0), np.float64(17.0), np.float64(1.9), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(11.8), np.float64(12.100000000000001), np.float64(12.100000000000001), np.float64(0.3), np.float64(2.1), np.float64(2.1), np.float64(2.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.1), np.float64(1.1), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.1), np.float64(2.6), np.float64(2.6), np.float64(1.5), np.float64(1.0), np.float64(3.8), np.float64(2.8), np.float64(2.8), np.float64(2.5), np.float64(2.5), np.float64(2.5), np.float64(0.0), np.float64(0.3), np.float64(0.3), np.float64(0.3), np.float64(0.0), np.float64(0.0), np.float64(4.4), np.float64(9.600000000000001), np.float64(34.5), np.float64(30.099999999999998), np.float64(24.9), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.3), np.float64(11.0), np.float64(15.7), np.float64(42.9), np.float64(76.4), np.float64(71.7), np.float64(44.2), np.float64(0.0), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.9), np.float64(1.4), np.float64(10.8), np.float64(12.100000000000001), np.float64(32.5), np.float64(39.5), np.float64(49.599999999999994), np.float64(43.7), np.float64(28.0), np.float64(18.9), np.float64(3.9000000000000004), np.float64(3.3000000000000003), np.float64(0.1), np.float64(0.1), np.float64(0.6), np.float64(2.2), np.float64(2.5), np.float64(2.0), np.float64(0.4), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.2), np.float64(5.1), np.float64(9.1), np.float64(6.9), np.float64(4.0), np.float64(2.0), np.float64(2.2), np.float64(2.2), np.float64(0.2), np.float64(3.8), np.float64(9.399999999999999), np.float64(10.099999999999998), np.float64(6.7), np.float64(1.1), np.float64(0.4), np.float64(0.0), np.float64(0.2), np.float64(0.2), np.float64(0.2), np.float64(0.0), np.float64(0.8), np.float64(0.9), np.float64(0.9), np.float64(0.5), np.float64(2.1), np.float64(30.700000000000003), np.float64(30.3), np.float64(28.6), np.float64(0.0), np.float64(0.0), np.float64(37.5), np.float64(37.6), np.float64(54.2), np.float64(16.700000000000003), np.float64(16.6), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(13.3), np.float64(13.3), np.float64(13.3), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(5.699999999999999), np.float64(5.699999999999999), np.float64(9.3), np.float64(5.2), np.float64(5.5), np.float64(2.5), np.float64(1.0), np.float64(0.7), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(11.8), np.float64(11.8), np.float64(11.8), np.float64(51.7), np.float64(75.7), np.float64(75.9), np.float64(24.2), np.float64(0.2), np.float64(11.3), np.float64(39.8), np.float64(39.8), np.float64(28.5), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.7), np.float64(1.7), np.float64(1.7), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.3), np.float64(0.3), np.float64(0.3), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.9), np.float64(0.9), np.float64(2.9), np.float64(2.1), np.float64(2.1), np.float64(0.2), np.float64(0.1), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(16.5), np.float64(16.5), np.float64(16.5), np.float64(0.0), np.float64(0.3), np.float64(0.4), np.float64(0.4), np.float64(0.7999999999999999), np.float64(0.7), np.float64(0.7), np.float64(0.4), np.float64(39.4), np.float64(40.4), np.float64(40.0), np.float64(3.5), np.float64(22.2), np.float64(22.2), np.float64(38.4), np.float64(18.7), np.float64(18.7), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(6.6), np.float64(7.1), np.float64(7.1), np.float64(0.5), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(9.8), np.float64(10.3), np.float64(36.8), np.float64(27.0), np.float64(26.5), np.float64(23.5), np.float64(23.5), np.float64(23.5), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.0), np.float64(2.0), np.float64(2.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.5), np.float64(0.4), np.float64(0.4), np.float64(0.4), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.3), np.float64(0.3), np.float64(0.3), np.float64(0.7), np.float64(0.7999999999999999), np.float64(7.3), np.float64(6.8), np.float64(6.7), np.float64(0.2), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(3.7), np.float64(19.9), np.float64(91.9), np.float64(98.0), np.float64(81.89999999999999), np.float64(9.9), np.float64(0.1), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0), np.float64(0.3), np.float64(0.4), np.float64(0.5), np.float64(0.2), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.0), np.float64(4.4), np.float64(4.4), np.float64(2.4), np.float64(0.0), np.float64(1.3), np.float64(1.3), np.float64(1.3), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(10.4), np.float64(10.4), np.float64(10.3), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(4.9), np.float64(4.9), np.float64(4.9), np.float64(0.5), np.float64(0.5), np.float64(0.8), np.float64(9.5), np.float64(9.5), np.float64(9.899999999999999), np.float64(0.7), np.float64(3.2), np.float64(5.2), np.float64(5.2), np.float64(2.7), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(12.3), np.float64(15.8), np.float64(15.8), np.float64(3.5), np.float64(0.0), np.float64(22.3), np.float64(22.3), np.float64(27.0), np.float64(18.7), np.float64(27.1), np.float64(22.5), np.float64(8.5), np.float64(6.5), np.float64(6.4), np.float64(6.4), np.float64(0.0), np.float64(1.2), np.float64(1.2), np.float64(1.2), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.3), np.float64(1.3), np.float64(1.3), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(1.7), np.float64(1.7), np.float64(1.7), np.float64(0.0), np.float64(0.0), np.float64(16.5), np.float64(16.5), np.float64(16.5), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.9), np.float64(1.9), np.float64(6.9), np.float64(34.9), np.float64(35.699999999999996), np.float64(30.7), np.float64(0.9), np.float64(20.3), np.float64(20.3), np.float64(20.2), np.float64(0.0), np.float64(0.0), np.float64(32.7), np.float64(68.30000000000001), np.float64(68.30000000000001), np.float64(37.9), np.float64(4.8), np.float64(5.1), np.float64(4.1), np.float64(1.7000000000000002), np.float64(2.3000000000000003), np.float64(1.4), np.float64(2.5), np.float64(1.6), np.float64(1.2), np.float64(0.0), np.float64(2.9), np.float64(8.1), np.float64(8.4), np.float64(12.6), np.float64(7.3999999999999995), np.float64(11.899999999999999), np.float64(4.8), np.float64(4.8), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(15.2), np.float64(26.2), np.float64(28.0), np.float64(12.8), np.float64(1.8), np.float64(0.1), np.float64(1.7000000000000002), np.float64(1.7000000000000002), np.float64(1.6), np.float64(6.5), np.float64(6.5), np.float64(10.6), np.float64(4.1), np.float64(4.1), np.float64(24.9), np.float64(26.099999999999998), np.float64(26.099999999999998), np.float64(7.2), np.float64(16.9), np.float64(19.299999999999997), np.float64(17.700000000000003), np.float64(6.800000000000001), np.float64(4.4), np.float64(0.0), np.float64(0.1), np.float64(0.2), np.float64(0.2), np.float64(0.1), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.8), np.float64(24.400000000000002), np.float64(24.400000000000002), np.float64(22.5), np.float64(1.1), np.float64(1.1), np.float64(0.6000000000000001), np.float64(0.4), np.float64(2.8), np.float64(20.2), np.float64(20.2), np.float64(17.8), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.7), np.float64(0.7), np.float64(0.7), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(12.7), np.float64(12.7), np.float64(12.7), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.3), np.float64(1.3), np.float64(12.700000000000001), np.float64(18.2), np.float64(18.3), np.float64(9.1), np.float64(2.3000000000000003), np.float64(2.2), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(0.2), np.float64(0.2), np.float64(0.1), np.float64(0.7), np.float64(0.7), np.float64(0.7), np.float64(38.0), np.float64(44.3), np.float64(44.3), np.float64(6.3), np.float64(0.0), np.float64(1.7), np.float64(3.0999999999999996), np.float64(4.6), np.float64(6.9), np.float64(5.6), np.float64(5.699999999999999), np.float64(5.7), np.float64(16.6), np.float64(26.2), np.float64(22.2), np.float64(11.2), np.float64(0.1), np.float64(0.1), np.float64(0.1), np.float64(0.4), np.float64(1.0), np.float64(1.1), np.float64(5.0), np.float64(5.3), np.float64(5.7), np.float64(9.3), np.float64(17.0), np.float64(16.7), np.float64(10.899999999999999), np.float64(6.0), np.float64(5.800000000000001), np.float64(3.7), np.float64(12.6), np.float64(12.6), np.float64(13.0), np.float64(0.4), np.float64(0.8), np.float64(0.4), np.float64(2.4), np.float64(2.0

Data                   2024-10-08
Temperatura media            17.5
Temperatura massima          21.5
Temperatura minima           14.9
Stagione                  Autunno
Precipitazioni (mm)           6.1
Precipitazioni 3gg          127.7
Name: 2851, dtype: object

7. Crea un DataFrame che contiene le precipitazioni cumulative annue (in termini di mm di pioggia totali). SUGGERIMENTO: puoi usare str.split("-") per separare giorno, mese, anno. Poi puoi usare `str[0]` per accedere all'anno.

In [ ]:
# ES7

8. Calcola le temperature medie annue per gli anni nel campione.

In [ ]:
# ES8

9. Il comune di bologna pubblica dati storici sugli agenti inquinanti [qui](https://opendata.comune.bologna.it/explore/dataset/dati-centraline-bologna-storico). Scarica il dataset in formato CSV (Esporta -> Tutto il dataset (CSV)), uniscilo a quello del meteo (attenzione: il separatore è ";"). Stampa le precipitazioni e la stagione del giorno in cui si è registrato il minimo di PM10 a porta S. Felice.

In [ ]:
# ES9


10. Calcola per quanti giorni le temperature massime sono state più alte della media per ciascun anno. Ordina il DataFrame risultante per numero di giorni decrescente.

In [ ]:
# ES10